name: Run build

on: [pull_request]

jobs:
  lint:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1    

      - name: Get the output
        run: |
          echo "name: ${{ steps.package.outputs.name }}"
          echo "version: ${{ steps.package.outputs.version }}"
          echo "npmjs-link: ${{ steps.package.outputs.npmjs-link }}"
          echo "is-release-candidate: ${{ steps.package.outputs.is-release-candidate }}"  

      - name: Check for rc version -e flase
        if: steps.package.outputs.is-release-candidate == false
        run: |
          echo "package is not a release candidate"

      - name: Check for rc version -ne false
        if: steps.package.outputs.is-release-candidate != false
        run: |
          echo "package is a release candidate"    
